### ISSUE TITLE
Review the Awesome List structure, scope and content

### ISSUE THREAD

**Issue by anjackson** [digipres/awesome-digital-preservation#2]
Review the Awesome List, to bring things together in sensible sections. Take out any text that doesn't make sense here, e.g. make it part of the digipres.org page instead.

Need to make the scope clear: Digital preservation not digitisation (although there's no Awesome List for that?). Not intended to be a comprehensive tool list (defer to COPTR), but can highlight tools that make it particularly easy to get started/experiment. (i.e. the focus is really getting started, and introducing other resources). Defer to the web archiving awesome list for web archiving detail.

Gaps:

- [x] Zenodo https://zenodo.org/communities/digital-preservation/
- [x] In-browser tools 
- [x] https://codewords.recurse.com/issues/seven/a-history-of-storage-media ?
- [x] https://github.com/amiaopensource/open-workflows
- [x] "Preservation Metadata" (e.g., related PREMIS, METS, PCDM)
- [x]  "Models and Standards" (e.g., OCFL, OAIS, TRUST)
- [ ] TDR certification?
- [ ] Links to glossaries
- [x] https://github.com/ross-spencer/brainscape-digital-preservation
- [x] Scope clarifications
- [x] Links to other awesome lists

**Comment by asciim0** [comment]
Looks great! 
Do you think "Preservation Metadata" (e.g., related PREMIS, METS, PCDM) and "Models and Standards" (e.g., OCFL, OAIS, TRUST) would be good additions? Also possibly TDR certification?

**Comment by anjackson** [comment]
Thanks @asciim0 - those are good ideas for additions. The Preservation Metadata section makes sense, but I think I'd probably prefer to introduce models and standards under more specific headings where appropriate. e.g. a Storage section with OCFL as a standard for storage.

That said, I'm not sure what good headings should be for the others (OAIS/TRUST/TDR)? I guess an audit and certification section, following DPC? https://www.dpconline.org/handbook/institutional-strategies/audit-and-certification Which makes me wonder if the Awesome List should just defer to the DPC handbook rather than repeat bits of it?

I guess we want to include pointers for all the jargon people are likely to hit early on? In which case they should all be mentioned briefly here, but readers should be referred elsewhere for detailed information?

**Comment by ross-spencer** [comment]
+1 in-browser tools.

> I guess we want to include pointers for all the jargon

`GLOSSARY.MD`? I don't believe we have an open source resource like that to point to? I also have a bunch of definitions to pull from, from my [Brainscape set](https://github.com/ross-spencer/brainscape-digital-preservation). Which I'm happy to let the content be used to. Also here to contribute to other definitions, maybe via Google Sheet first? If there's not a glossary I am missing. (SAA and DPC glossaries I guess are good too, but not open to contribution)

**Comment by anjackson** [comment]
Thansk @ross-spencer - I like the idea of an open glossary, although your Brainscape set seems pretty close to being that already, so I'd be keen to find a solution that is compatible with that. e.g. maybe we should publicised contributions to that rather than reproduce it here?

**Comment by ross-spencer** [comment]
> so I'd be keen to find a solution that is compatible with that.

That would always be nice, but it's an under utilized/unknown resource. An open format, that could be converted back to something "Branscape-like" or other platform would be awesome! 

>  the DPC glossary is open for contributions in that you can suggest additions or modifications by email

It's not for me to dissect the issues with that mechanism. 

>  whether we want to build a glossary with some kind of open governance, and if there's a few folks willing to put the time into making it work.

+1 here.

Perhaps the DPC have an appetite to look at doing something more open-source-y with theirs? It may be an approach to use that as a seed? 

Do we know of other glossaries that other folk use? Perhaps there are some in multiple languages too? If so, maybe one approach is a digital preservation glossary section that links to the these many resources?

**Comment by anjackson** [comment]
I'm working on a PR (#3) for this issue, see https://github.com/digipres/awesome-digital-preservation/blob/restructure/README.md#awesome-digital-preservation-- 

The glossary idea is good but I might break it out into it's own issue as I'm not sure how to proceed.

**Comment by anjackson** [comment]
Hi @asciim0  - I've added some of those links, but TBH I wasn't sure what to link to for 'TRUST' and 'TDR'.  Can you take a look at it? 

https://github.com/digipres/awesome-digital-preservation/blob/ed84c5264c8ce907c036404ccc6f7834e1f0e6fb/README.md?plain=1#L138-L140

I'm also not really sure what to do with the glossaries. I've added the DPC one for now.

**Comment by ross-spencer** [comment]
> I'm also not really sure what to do with the glossaries. I've added the DPC one for now.

I noticed the Tweet - how do we get folks to engage with Github?

Perhaps another issue or a discussion here Andy? - If I were to propose a workflow (also happy to help):

1. I can create a Google Sheet with a seed from Brainscape, e.g. merged CSVs. 
1. Create issue here - with sheet. 
1. Ask folks to contribute over the course of, say, 1 month?
1. Then maybe we can find a layout for a Glossary that works, and we can script the definitions into that?

**Comment by ross-spencer** [comment]
> I can create a Google Sheet with a seed from Brainscape, e.g. merged CSVs.

If there's an appetite: https://docs.google.com/spreadsheets/d/1myDAS_2Y1TpZfhqFZ4XsTlK1pa9a7Bio0HeIzy767qc/edit?usp=sharing

**Comment by anjackson** [comment]
Okay, I'm going to tidy this issue up because I didn't want that re-structured version hanging off as a fork for too long. As soon as I can, I'll move the Glossary stuff to a discussion and encourage people to get involved.

I'll  open a fresh ticket for the audit and certification bit too. At that point this ticket can be closed.

**Comment by ross-spencer** [comment]
@anjackson I found a pretty cool single page-glossary template and converted some of the brainscape data to work inside it, removing some duplicates and then manually adding lnter-document links (see also links):

* https://ross-spencer.github.io/digipres-glossary/

Very happy to pass custody of something like this along, and discuss a way to get some more community input. 

The template is here: https://github.com/hilverd/glossary-page-template

**Comment by anjackson** [comment]
Shifting the glossary discussion over to https://github.com/orgs/digipres/discussions/41
